name: Checks

on:
  pull_request:
    branches: [ master ]
  workflow_call:

jobs:
  lint-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: ./.github/actions/cache-clojure-deps
        with:
          key-label: 'lint'
      - uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1
        with:
          install_args: "babashka cljfmt clj-kondo java clojure"
      - name: Lint and format
        run: bb fmt-check && bb deps && bb lint-init && bb lint

  outdated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: ./.github/actions/cache-clojure-deps
        with:
          key-label: 'outdated'
      - uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1
        with:
          install_args: "babashka java clojure"
      - name: Outdated deps
        run: bb deps && bb outdated-check

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: ./.github/actions/cache-clojure-deps
        with:
          key-label: 'tests'
      - uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1
        with:
          install_args: "babashka java clojure"
      - name: Run tests
        run: bb deps && bb test
