name: Cache Clojure deps

inputs:
  key-label:
    description: 'Additional label for cache key'
    default: 'deps'

runs:
  using: composite
  steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: Cache Clojure deps
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.clojure
          ~/.cpcache
        key: ${{ runner.os }}-clojure-${{ inputs.key-label }}-${{ hashFiles('**/deps.edn') }}
